# Generated by Django 4.2.7 on 2026-01-22 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('coding', '0001_initial'),
        ('users', '0002_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interviews', models.PositiveIntegerField(default=0)),
                ('completed_interviews', models.PositiveIntegerField(default=0)),
                ('average_interview_score', models.FloatField(default=0)),
                ('total_coding_problems', models.PositiveIntegerField(default=0)),
                ('solved_coding_problems', models.PositiveIntegerField(default=0)),
                ('coding_success_rate', models.FloatField(default=0)),
                ('total_chat_sessions', models.PositiveIntegerField(default=0)),
                ('total_chat_messages', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('favorite_difficulty', models.CharField(blank=True, max_length=20)),
                ('favorite_topic', models.CharField(blank=True, max_length=100)),
                ('improvement_areas', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('weekly_goal_completion', models.FloatField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('problem_solving_score', models.FloatField(default=0)),
                ('behavioral_score', models.FloatField(default=0)),
                ('response_times', models.JSONField(default=list)),
                ('question_types_distribution', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('ai_feedback_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.interview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodingPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time', models.FloatField(blank=True, null=True)),
                ('best_memory', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_to_solve', models.PositiveIntegerField(default=0)),
                ('time_to_first_attempt', models.FloatField(blank=True, null=True)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('solution_quality_score', models.FloatField(default=0)),
                ('code_efficiency_score', models.FloatField(default=0)),
                ('readability_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.codingproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
