# Generated by Django 4.2.7 on 2026-01-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_samples', models.JSONField(default=list, help_text='List of voice sample file paths')),
                ('accent', models.CharField(blank=True, max_length=50)),
                ('speaking_rate', models.FloatField(blank=True, null=True)),
                ('pitch_range', models.CharField(blank=True, max_length=50)),
                ('common_phrases', models.JSONField(default=list)),
                ('is_calibrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextToSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tts_audio/')),
                ('voice', models.CharField(default='en-US-Standard-C', max_length=50)),
                ('speed', models.FloatField(default=1.0)),
                ('pitch', models.FloatField(default=0.0)),
                ('provider', models.CharField(default='google', max_length=20)),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeechSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('interview', 'Interview Response'), ('chat', 'Chat Message'), ('practice', 'Practice Session'), ('feedback', 'Voice Feedback')], max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speech_audio/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('provider', models.CharField(default='google', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeechAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_duration', models.FloatField(default=0)),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('most_used_language', models.CharField(blank=True, max_length=10)),
                ('error_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
